## 异常的分类
Throwable时所有异常类的父类，异常分为Error和Exception两种类型
##### Error
Error类通常来描述java运行时系统中的内部错误以及资源耗尽错误，一般是指JVM错误。仅靠修改程序本身不能恢复执行，此类被称为致命性异常。

##### Exception
称为非致命性异常。该类型的异常在程序中发生后可以进行捕获，处理后程序正常进行。Exception分为RuntimeException异常（运行时异常）和
Runtime Exception之外的异常（编译时异常）。

##### 异常类型
Exception异常层次结构的父类；NullPointException访问Null对象的方法；IllegalArgumentException接收非法参数；ClassNotFoundException不能加载所需要的类；
ArithmetticException算术运算异常，如除数为零；ArrayIndexOutOfBoundsException数组下标小于或大于其长度；InputMisMatchException允许接收的数据类型与
实际输入的类型不匹配；NumberFormatException格式化数据异常

##### 异常处理的步骤
> 1.一旦产生异常，首先产生对应异常类的实例对象。<br>
> 2.在try-catch-finally语句中捕获此异常对象。<br>
> 3.产生的异常对象与catch语句中各个异常类型进行匹配，若匹配成功，执行catch语句，否则执行finally语句。
```java
package OOP3;

public class Demo {
	public static void main(String[] args) {
		try {
			int a=50;
			int result=a/0;      //发生异常，生成异常类的实例化对象
		} catch (Exception e) {    //匹配并捕捉异常对象
			e.printStackTrace();      //执行异常处理
		}finally{                   // 异常统一出口
			System.out.println("没有找到匹配的异常");
		}
	}
}

```
```java
package OOP3;

public class ExceptionDemo {
	public static void main(String[] args) {
		System.out.println("开始计算");
		int firstNum=0;
		int secondNum=0;
		try{
			String str1=args[0];
			String str2=args[1];
			firstNum=Integer.parseInt(str1);
			secondNum=Integer.parseInt(str2);
			int result = firstNum/secondNum;  
			System.out.println("两个数字相除为"+result);
		}catch(ArithmeticException e){       
			System.out.println("算术异常");     
		}catch(NumberFormatException e){
			System.out.println("格式化数据异常");
		}catch(Exception e){
			System.out.println("其他异常");
		}
		System.out.println("计算结束");
	}
}

```
